// Generated by template.py. DO NOT EDIT!
using System;
using System.Collections.Generic;
using System.Xml;

public sealed class BuffTemplate
{
	public uint nId;	//id
	public string szName;	//名字
	public string szDesc;	//描述
	public uint nType;	//enum BuffType
	public uint nTrigger;	//enum BuffTriggerType
	public uint nTriggerParam1;	//触发类型参数1
	public uint nTriggerParam2;	//触发类型参数2
	public int iEffectA;	//效果值A
	public int iEffectB;	//效果值B（buffid etc..）
	public int iBout;	//持续回合
	public string szImg;	//图片名
}


public sealed class BuffTemplateData
{
	public static Dictionary<uint, BuffTemplate> Data = new Dictionary<uint, BuffTemplate>();

	public static void Init(XmlNode xml)
	{
		foreach (XmlElement element in xml.ChildNodes)
		{
			BuffTemplate template = new BuffTemplate();
			template.nId = element["nId"] != null ? uint.Parse(element["nId"].InnerText) : 0;	//id
			template.szName = element["szName"] != null ? element["szName"].InnerText : "";	//名字
			template.szDesc = element["szDesc"] != null ? element["szDesc"].InnerText : "";	//描述
			template.nType = element["nType"] != null ? uint.Parse(element["nType"].InnerText) : 0;	//enum BuffType
			template.nTrigger = element["nTrigger"] != null ? uint.Parse(element["nTrigger"].InnerText) : 0;	//enum BuffTriggerType
			template.nTriggerParam1 = element["nTriggerParam1"] != null ? uint.Parse(element["nTriggerParam1"].InnerText) : 0;	//触发类型参数1
			template.nTriggerParam2 = element["nTriggerParam2"] != null ? uint.Parse(element["nTriggerParam2"].InnerText) : 0;	//触发类型参数2
			template.iEffectA = element["iEffectA"] != null ? int.Parse(element["iEffectA"].InnerText) : 0;	//效果值A
			template.iEffectB = element["iEffectB"] != null ? int.Parse(element["iEffectB"].InnerText) : 0;	//效果值B（buffid etc..）
			template.iBout = element["iBout"] != null ? int.Parse(element["iBout"].InnerText) : 0;	//持续回合
			template.szImg = element["szImg"] != null ? element["szImg"].InnerText : "";	//图片名

			Data.Add(template.nId, template);
		}
	}

	public static BuffTemplate GetData(uint nId, object className = null)
	{
		if (!Data.ContainsKey(nId))
		{
			if (className != null)
				UnityEngine.Debug.LogError(string.Format("BuffTemplate is null, Id = {0} @ {1}", "nId="+nId, className));
			return null;
		}
		BuffTemplate template = Data[nId];
		return template;
	}
}