// Generated by template.py. DO NOT EDIT!
using System.Collections.Generic;
using System.Xml;

public sealed class CardEffectTemplate
{
	public uint nId;	//id
	public uint nType;	//效果类型 enum of CardEffectType
	public int iEffectValue;	//效果值
	public uint nLinkId;	//关联效果ID
}


public sealed class CardEffectTemplateData
{
	public static Dictionary<uint, CardEffectTemplate> Data = new Dictionary<uint, CardEffectTemplate>();

	public static void Init(XmlNode xml)
	{
		foreach (XmlElement element in xml.ChildNodes)
		{
			CardEffectTemplate template = new CardEffectTemplate();
			template.nId = element["nId"] != null ? uint.Parse(element["nId"].InnerText) : 0;	//id
			template.nType = element["nType"] != null ? uint.Parse(element["nType"].InnerText) : 0;	//效果类型 enum of CardEffectType
			template.iEffectValue = element["iEffectValue"] != null ? int.Parse(element["iEffectValue"].InnerText) : 0;	//效果值
			template.nLinkId = element["nLinkId"] != null ? uint.Parse(element["nLinkId"].InnerText) : 0;	//关联效果ID

			Data.Add(template.nId, template);
		}
	}

	public static CardEffectTemplate GetData(uint nId, object className = null)
	{
		if (!Data.ContainsKey(nId))
		{
			if (className != null)
				UnityEngine.Debug.LogError(string.Format("CardEffectTemplate is null, Id = {0} @ {1}", "nId="+nId, className));
			return null;
		}
		CardEffectTemplate template = Data[nId];
		return template;
	}
}