// Generated by template.py. DO NOT EDIT!
using System.Collections.Generic;
using System.Xml;

public sealed class CardEffectTemplate
{
	public uint nId;	//id
	public uint iEffectTrigType;	//效果触发类型 enum CardEffectTrigType
	public uint nTarget;	//目标类型 enum CardEffectTargetType
	public uint nType;	//效果类型 enum CardEffectType
	public int iEffectValue;	//效果值
	public int iEffectCount;	//效果触发次数
	public int iCostEffectTimes;	//费用效果倍数
	public int iEffectValue_2;	//2级效果值
	public uint nLinkId;	//关联效果ID
}


public sealed class CardEffectTemplateData
{
	public static Dictionary<uint, CardEffectTemplate> Data = new Dictionary<uint, CardEffectTemplate>();

	public static void Init(XmlNode xml)
	{
		foreach (XmlElement element in xml.ChildNodes)
		{
			CardEffectTemplate template = new CardEffectTemplate();
			template.nId = element["nId"] != null ? uint.Parse(element["nId"].InnerText) : 0;	//id
			template.iEffectTrigType = element["iEffectTrigType"] != null ? uint.Parse(element["iEffectTrigType"].InnerText) : 0;	//效果触发类型 enum CardEffectTrigType
			template.nTarget = element["nTarget"] != null ? uint.Parse(element["nTarget"].InnerText) : 0;	//目标类型 enum CardEffectTargetType
			template.nType = element["nType"] != null ? uint.Parse(element["nType"].InnerText) : 0;	//效果类型 enum CardEffectType
			template.iEffectValue = element["iEffectValue"] != null ? int.Parse(element["iEffectValue"].InnerText) : 0;	//效果值
			template.iEffectCount = element["iEffectCount"] != null ? int.Parse(element["iEffectCount"].InnerText) : 0;	//效果触发次数
			template.iCostEffectTimes = element["iCostEffectTimes"] != null ? int.Parse(element["iCostEffectTimes"].InnerText) : 0;	//费用效果倍数
			template.iEffectValue_2 = element["iEffectValue_2"] != null ? int.Parse(element["iEffectValue_2"].InnerText) : 0;	//2级效果值
			template.nLinkId = element["nLinkId"] != null ? uint.Parse(element["nLinkId"].InnerText) : 0;	//关联效果ID

			Data.Add(template.nId, template);
		}
	}

	public static CardEffectTemplate GetData(uint nId, object className = null)
	{
		if (!Data.ContainsKey(nId))
		{
			if (className != null)
				UnityEngine.Debug.LogError(string.Format("CardEffectTemplate is null, Id = {0} @ {1}", "nId="+nId, className));
			return null;
		}
		CardEffectTemplate template = Data[nId];
		return template;
	}
}