// Generated by template.py. DO NOT EDIT!
using System.Collections.Generic;
using System.Xml;

public sealed class EnemyTemplate
{
	public uint nId;	//id
	public int iHp;	//生命
}


public sealed class EnemyTemplateData
{
	public static Dictionary<uint, EnemyTemplate> Data = new Dictionary<uint, EnemyTemplate>();

	public static void Init(XmlNode xml)
	{
		foreach (XmlElement element in xml.ChildNodes)
		{
			EnemyTemplate template = new EnemyTemplate();
			template.nId = element["nId"] != null ? uint.Parse(element["nId"].InnerText) : 0;	//id
			template.iHp = element["iHp"] != null ? int.Parse(element["iHp"].InnerText) : 0;	//生命

			Data.Add(template.nId, template);
		}
	}

	public static EnemyTemplate GetData(uint nId, object className = null)
	{
		if (!Data.ContainsKey(nId))
		{
			if (className != null)
				UnityEngine.Debug.LogError(string.Format("EnemyTemplate is null, Id = {0} @ {1}", "nId="+nId, className));
			return null;
		}
		EnemyTemplate template = Data[nId];
		return template;
	}
}