// Generated by template.py. DO NOT EDIT!
using System;
using System.Collections.Generic;
using System.Xml;

public sealed class RelicTemplate
{
	public uint nId;	//法宝ID
	public uint nType;	//法宝类型
	public string szName;	//名字
	public string szDesc;	//描述
	public string szImg;	//图片名
}


public sealed class RelicTemplateData
{
	public static Dictionary<uint, RelicTemplate> Data = new Dictionary<uint, RelicTemplate>();

	public static void Init(XmlNode xml)
	{
		foreach (XmlElement element in xml.ChildNodes)
		{
			RelicTemplate template = new RelicTemplate();
			template.nId = element["nId"] != null ? uint.Parse(element["nId"].InnerText) : 0;	//法宝ID
			template.nType = element["nType"] != null ? uint.Parse(element["nType"].InnerText) : 0;	//法宝类型
			template.szName = element["szName"] != null ? element["szName"].InnerText : "";	//名字
			template.szDesc = element["szDesc"] != null ? element["szDesc"].InnerText : "";	//描述
			template.szImg = element["szImg"] != null ? element["szImg"].InnerText : "";	//图片名

			Data.Add(template.nId, template);
		}
	}

	public static RelicTemplate GetData(uint nId, object className = null)
	{
		if (!Data.ContainsKey(nId))
		{
			if (className != null)
				UnityEngine.Debug.LogError(string.Format("RelicTemplate is null, Id = {0} @ {1}", "nId="+nId, className));
			return null;
		}
		RelicTemplate template = Data[nId];
		return template;
	}
}