// Generated by template.py. DO NOT EDIT!
using System;
using System.Collections.Generic;
using System.Xml;

public sealed class TemplateList
{
	public List<string> XMLList = new List<string>() {
		"BuffTemplate_table.xml",
		"CardEffectTemplate_table.xml",
		"CardTemplate_table.xml",
		"EnemyTemplate_table.xml",
	};

	public List<Action<XmlNode>>  FunctionList = new List<Action<XmlNode>>() {
		BuffTemplateData.Init,
		CardEffectTemplateData.Init,
		CardTemplateData.Init,
		EnemyTemplateData.Init,
	};
}
